### ISSUE TITLE
Some dataset problems when testing

### ISSUE THREAD

**Issue by cuiliangxian** [JiehongLin/VI-Net#1]
The code in TestDataset:
        result_pkl_list = glob.glob(os.path.join(self.data_dir, 'segmentation_results', dataset, 'results_*.pkl'))
        self.result_pkl_list = sorted(result_pkl_list)
seems not to coincidence with data processing in self-DPDN. Can u help me with the correct dataset architecture?

**Comment by JiehongLin** [comment]
The used test segmentation results are the same as DualPoseNet and DPDN [[link](https://drive.google.com/file/d/1RwAbFWw2ITX9mXzLUEBjPy_g-MNdyHET/view?usp=sharing)]. 
You may need to change the file structure and names.
