### ISSUE TITLE
关于模型评估的checkpoints

### ISSUE THREAD

**Issue by Yanshiwen** [JiehongLin/VI-Net#2]
作者您好，
在阅读了您的工作代码后我好像并没有看见可以用于模型评估的checkpoints，请问您可以提供有效的checkpoints和results文件夹以辅助检验论文中报告的结果吗？非常感谢！

**Comment by JiehongLin** [comment]
Hi, 我们已经将checkpoints和results上传，你可以从这个[link](https://drive.google.com/file/d/1t7Q6VxJXJFDh1nripFiLtaKPrrUgeYXR/view?usp=sharing)下载。
