### ISSUE TITLE
Training report error

### ISSUE THREAD

**Issue by AFESDTTM** [JiehongLin/VI-Net#4]
Hello,I would like to ask what are the following questions。

![image](https://github.com/JiehongLin/VI-Net/assets/106895081/aea8eb06-6c44-4cf0-b974-8730930cc20e)

**Comment by JiehongLin** [comment]
It appears that the Pointnet2 library hasn't been installed successfully. You may first install Pointnet2 before training the model as done in [code](https://github.com/JiehongLin/VI-Net/blob/60ac458b52ae9d57df7eeb356e386f82ae914b8d/dependencies..sh#L5).
