### ISSUE TITLE
Hello,How to obtain the point cloud in your paper?

### ISSUE THREAD

**Issue by AFESDTTM** [JiehongLin/VI-Net#5]
How to obtain the point cloud in your paper? Was it generated using code? If so, could you provide the code
![image](https://github.com/JiehongLin/VI-Net/assets/106895081/687909f6-847a-4058-a2c0-326019d550f1)

**Comment by JiehongLin** [comment]
The point clouds are visualized using MeshLab. The colors can be assigned by mapping the NOCS values to the range of [0, 255].

**Comment by AFESDTTM** [comment]
thanks
